src/Entity/Tasks.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TasksRepository")
 */
class Tasks
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    public function __construct()
    {
        $this->updated_at = new \DateTime();
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Entity/TasksSearch.php
<?php
namespace App\Entity;

class TasksSearch {

    /**
     * @var string|null
     */
    private $status;

    /**
     * @return string|null
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * @param string|null $status
     * @return TasksSearch
     */
    public function setStatus(string $status): TasksSearch
    {
        $this->status = $status;
        return $this;
    }

}

src/Form/TasksSearchType.php
<?php

namespace App\Form;

use App\Entity\TasksSearch;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TasksSearchType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('status', ChoiceType::class, [
                'choices' => ['à faire' => 'à faire', 'en cours' => 'en cours', 'terminée' => 'terminée'],
                'label' => false,
                'required' => false,
                'placeholder' => 'Tout'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => TasksSearch::class,
            'method' => 'get',
            'csrf_protection' => false
        ]);
    }

    public function getBlockPrefix()
    {
        return '';
    }
}

src/Form/TasksType.php
<?php

namespace App\Form;

use App\Entity\Tasks;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TasksType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', null, [
                'label' => 'Titre'
            ])
            ->add('description')
            ->add('status', ChoiceType::class, [
                'choices' => ['à faire' => 'à faire', 'en cours' => 'en cours', 'terminée' => 'terminée'],
                'label' => 'Statut'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Tasks::class,
        ]);
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\TasksSearch;
use App\Form\TasksSearchType;
use App\Repository\TasksRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home", methods={"GET"})
     */
    public function index(TasksRepository $repository, PaginatorInterface $paginator, Request $request) : Response
    {
        $search = new TasksSearch();
        $form = $this->createForm(TasksSearchType::class, $search);
        $form->handleRequest($request);

        $tasks = $paginator->paginate(
            $repository->findAllQuery($search),
            $request->query->getInt('page', 1),
            5
        );

        return $this->render('home/index.html.twig', [
            'tasks' => $tasks,
            'form' => $form->createView()
        ]);
    }
}

src/Controller/TasksController.php
<?php

namespace App\Controller;

use App\Entity\Tasks;
use App\Form\TasksType;
use App\Repository\TasksRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/tasks")
 */
class TasksController extends AbstractController
{

    /**
     * @Route("/new", name="tasks_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $task = new Tasks();
        $form = $this->createForm(TasksType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($task);
            $entityManager->flush();

            return $this->redirectToRoute('home');
        }

        return $this->render('tasks/new.html.twig', [
            'task' => $task,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="tasks_show", methods={"GET"})
     */
    public function show(Tasks $task): Response
    {
        return $this->render('tasks/show.html.twig', [
            'task' => $task,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="tasks_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Tasks $task): Response
    {
        $task->setUpdatedAt(new \DateTime());
        $form = $this->createForm(TasksType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('home');
        }

        return $this->render('tasks/edit.html.twig', [
            'task' => $task,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="tasks_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Tasks $task): Response
    {
        if ($this->isCsrfTokenValid('delete'.$task->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($task);
            $entityManager->flush();
        }

        return $this->redirectToRoute('home');
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
        <link rel="stylesheet" href="{{ asset('css/lux.css') }}">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand" href="{{ path('home') }}">My Tasks</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link active" href="{{ path('home') }}">Mes tâches</a>
                    </li>
                </ul>
            </div>
        </nav>

        {% block body %}{% endblock %}

        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}My Tasks | MyBestPro{% endblock %}

{% block body %}

<div class="jumbotron p-0 pt-4">
    <div class="container">
        {{ form_start(form) }}
        <div class="form-row">
            <div class="col">
                <label for="search">Filtrer par statut</label>
            </div>
            <div class="col">
                {{ form_row(form.status) }}
            </div>
            <div class="col">
                <button class="btn btn-outline-info btn-sm">Recherche</button>
            </div>
        </div>
        {{ form_end(form) }}
    </div>
</div>
<div class="container mt-4">
    <h1 class="row justify-content-center">Tâches</h1>
    <table class="table table-hover">
        <thead>
        <tr class="table-dark">
            <th>Titre</th>
            <th>Déscription</th>
            <th>Statut</th>
            <th>Création</th>
            <th>Modification</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        {% for task in tasks %}
            <tr class="{% if task.status == 'terminée' %}table-success{% elseif task.status == 'en cours' %}table-warning{% endif %}">
                <td>{{ task.title }}</td>
                <td>{{ task.description }}</td>
                <td>{{ task.status }}</td>
                <td>{{ task.createdAt ? task.createdAt|date('d/m/Y à H:i') : '' }}</td>
                <td> {% if task.createdAt == task.updatedAt %}
                        Pas encore modifier
                    {% else %}
                        {{ task.updatedAt ? task.updatedAt|date('d/m/Y à H:i') : '' }}</td>
                    {% endif %}
                <td>
                    <a class="btn btn-outline-primary" href="{{ path('tasks_edit', {'id': task.id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">Aucune tache trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <div class="row justify-content-end">
        <a class="btn btn-primary mr-5" href="{{ path('tasks_new') }}">Create new</a>
    </div>

    <div class="pagination row justify-content-center">
        {{ knp_pagination_render(tasks) }}
    </div>
</div>

{% endblock %}

templates/tasks/_delete_form.html.twig
<form class="row justify-content-end" method="post" action="{{ path('tasks_delete', {'id': task.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cette tache ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ task.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/tasks/_form.html.twig
{{ form_start(form) }}
    <fieldset class="container">
        <div class="row">
            <div class="col-6">{{ form_row(form.title) }}</div>
            <div class="col-6">{{ form_row(form.status) }}</div>
        </div>
        {{ form_widget(form) }}
        <div class="row justify-content-end">
            <button class="btn btn-primary mr-5 mt-5">{{ button_label|default('Enregistrer') }}</button>
        </div>
    </fieldset>
{{ form_end(form) }}

templates/tasks/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier tâche{% endblock %}

{% block body %}
    <div class="container">
        {{ include('tasks/_delete_form.html.twig') }}

        <h1 class="row justify-content-center mb-5">Modifier {{ task.title }}</h1>

        {{ include('tasks/_form.html.twig', {'button_label': 'Modifier'}) }}
    </div>
{% endblock %}

templates/tasks/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle tâche{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="row justify-content-center mt-4 mb-5">Crée une nouvelle tâche</h1>

        {{ include('tasks/_form.html.twig') }}
    </div>
{% endblock %}